var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(e,h,m){if(null==e)throw new TypeError("The 'this' value for String.prototype."+m+" must not be null or undefined");if(h instanceof RegExp)throw new TypeError("First argument to String.prototype."+m+" must not be a regular expression");return e+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,h,m){e!=Array.prototype&&e!=Object.prototype&&(e[h]=m.value)};$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(e,h,m,u){if(h){m=$jscomp.global;e=e.split(".");for(u=0;u<e.length-1;u++){var v=e[u];v in m||(m[v]={});m=m[v]}e=e[e.length-1];u=m[e];h=h(u);h!=u&&null!=h&&$jscomp.defineProperty(m,e,{configurable:!0,writable:!0,value:h})}};
$jscomp.polyfill("String.prototype.endsWith",function(e){return e?e:function(e,m){var h=$jscomp.checkStringArgs(this,e,"endsWith");e+="";void 0===m&&(m=h.length);m=Math.max(0,Math.min(m|0,h.length));for(var v=e.length;0<v&&0<m;)if(h[--m]!=e[--v])return!1;return 0>=v}},"es6","es3");
$jscomp.polyfill("String.prototype.startsWith",function(e){return e?e:function(e,m){var h=$jscomp.checkStringArgs(this,e,"startsWith");e+="";var v=h.length,l=e.length;m=Math.max(0,Math.min(m|0,h.length));for(var n=0;n<l&&m<v;)if(h[m++]!=e[n++])return!1;return n>=l}},"es6","es3");
$jscomp.polyfill("String.prototype.repeat",function(e){return e?e:function(e){var h=$jscomp.checkStringArgs(this,null,"repeat");if(0>e||1342177279<e)throw new RangeError("Invalid count value");e|=0;for(var u="";e;)if(e&1&&(u+=h),e>>>=1)h+=h;return u}},"es6","es3");
(function(){function e(b){function a(a){return function(d){return b(a,d)}}a.arity=2;a.func=b;return a}function h(b){function a(a){return function(d){return function(c){return b(a,d,c)}}}a.arity=3;a.func=b;return a}function m(b){function a(a){return function(d){return function(c){return function(g){return b(a,d,c,g)}}}}a.arity=4;a.func=b;return a}function u(b){function a(a){return function(d){return function(c){return function(g){return function(e){return b(a,d,c,g,e)}}}}}a.arity=5;a.func=b;return a}
function v(b){function a(a){return function(d){return function(c){return function(g){return function(e){return function(y){return b(a,d,c,g,e,y)}}}}}}a.arity=6;a.func=b;return a}function l(b,a,c){return 2===b.arity?b.func(a,c):b(a)(c)}function n(b,a,c,d){return 3===b.arity?b.func(a,c,d):b(a)(c)(d)}function G(b,a,c,d,g){return 4===b.arity?b.func(a,c,d,g):b(a)(c)(d)(g)}function I(b,a,c,d,g,e){return 5===b.arity?b.func(a,c,d,g,e):b(a)(c)(d)(g)(e)}var p=function(){function b(a,d){if(0===d)throw Error("Cannot perform mod 0. Division by zero error.");
var c=a%d;a=0===a?0:0<d?0<=a?c:c+d:-b(-a,-d);return a===d?0:a}var a=["LT","EQ","GT"];return{div:e(function(a,b){return a/b|0}),rem:e(function(a,b){return a%b}),mod:e(b),pi:Math.PI,e:Math.E,cos:Math.cos,sin:Math.sin,tan:Math.tan,acos:Math.acos,asin:Math.asin,atan:Math.atan,atan2:e(Math.atan2),degrees:function(a){return a*Math.PI/180},turns:function(a){return 2*Math.PI*a},fromPolar:function(a){var b=a._0;a=a._1;return k.Tuple2(b*Math.cos(a),b*Math.sin(a))},toPolar:function(a){var b=a._0;a=a._1;return k.Tuple2(Math.sqrt(b*
b+a*a),Math.atan2(a,b))},sqrt:Math.sqrt,logBase:e(function(a,b){return Math.log(b)/Math.log(a)}),negate:function(a){return-a},abs:function(a){return 0>a?-a:a},min:e(function(a,b){return 0>k.cmp(a,b)?a:b}),max:e(function(a,b){return 0<k.cmp(a,b)?a:b}),clamp:h(function(a,b,g){return 0>k.cmp(g,a)?a:0<k.cmp(g,b)?b:g}),compare:e(function(b,d){return{ctor:a[k.cmp(b,d)+1]}}),xor:e(function(a,b){return a!==b}),not:function(a){return!a},truncate:function(a){return a|0},ceiling:Math.ceil,floor:Math.floor,round:Math.round,
toFloat:function(a){return a},isNaN:isNaN,isInfinite:function(a){return Infinity===a||-Infinity===a}}}(),k=function(){function b(a,d,c,g){if(100<c)return g.push({x:a,y:d}),!0;if(a===d)return!0;if("object"!==typeof a){if("function"===typeof a)throw Error('Trying to use `(==)` on functions. There is no way to know if functions are "the same" in the Elm sense. Read more about this at http://package.elm-lang.org/packages/elm-lang/core/latest/Basics#== which describes why it is this way and what the better version will look like.');
return!1}if(null===a||null===d)return!1;if(a instanceof Date)return a.getTime()===d.getTime();if(!("ctor"in a)){for(var y in a)if(!b(a[y],d[y],c+1,g))return!1;return!0}if("RBNode_elm_builtin"===a.ctor||"RBEmpty_elm_builtin"===a.ctor)a=_elm_lang$core$Dict$toList(a),d=_elm_lang$core$Dict$toList(d);"Set_elm_builtin"===a.ctor&&(a=_elm_lang$core$Set$toList(a),d=_elm_lang$core$Set$toList(d));if("::"===a.ctor){for(;"::"===a.ctor&&"::"===d.ctor;){if(!b(a._0,d._0,c+1,g))return!1;a=a._1;d=d._1}return a.ctor===
d.ctor}if("_Array"===a.ctor){a=_elm_lang$core$Native_Array.toJSArray(a);d=_elm_lang$core$Native_Array.toJSArray(d);if(a.length!==d.length)return!1;for(y=0;y<a.length;y++)if(!b(a[y],d[y],c+1,g))return!1;return!0}if(!b(a.ctor,d.ctor,c+1,g))return!1;for(y in a)if(!b(a[y],d[y],c+1,g))return!1;return!0}function a(b,d){if("object"!==typeof b)return b===d?0:b<d?-1:1;if(b instanceof String)return b=b.valueOf(),d=d.valueOf(),b===d?0:b<d?-1:1;if("::"===b.ctor||"[]"===b.ctor){for(;"::"===b.ctor&&"::"===d.ctor;){var c=
a(b._0,d._0);if(0!==c)return c;b=b._1;d=d._1}return b.ctor===d.ctor?0:"[]"===b.ctor?-1:1}if("_Tuple"===b.ctor.slice(0,6)){var g=b.ctor.slice(6)-0;if(0===g)return 0;if(1<=g){c=a(b._0,d._0);if(0!==c)return c;if(2<=g){c=a(b._1,d._1);if(0!==c)return c;if(3<=g){c=a(b._2,d._2);if(0!==c)return c;if(4<=g){c=a(b._3,d._3);if(0!==c)return c;if(5<=g){c=a(b._4,d._4);if(0!==c)return c;if(6<=g){c=a(b._5,d._5);if(0!==c)return c;if(7<=g)throw Error("Comparison error: cannot compare tuples with more than 6 elements.");
}}}}}}return 0}throw Error("Comparison error: comparison is only defined on ints, floats, times, chars, strings, lists of comparable values, and tuples of comparable values.");}function c(a){return a.start.line==a.end.line?"on line "+a.start.line:"between lines "+a.start.line+" and "+a.end.line}function d(a){var b=typeof a;if("function"===b)return"<function>";if("boolean"===b)return a?"True":"False";if("number"===b)return a+"";if(a instanceof String)return"'"+g(a,!0)+"'";if("string"===b)return'"'+
g(a,!1)+'"';if(null===a)return"null";if("object"===b&&"ctor"in a){b=a.ctor.substring(0,5);if("_Tupl"===b){b=[];for(var c in a)"ctor"!==c&&b.push(d(a[c]));return"("+b.join(",")+")"}if("_Task"===b)return"<task>";if("_Array"===a.ctor)return a=_elm_lang$core$Array$toList(a),"Array.fromList "+d(a);if("<decoder>"===a.ctor)return"<decoder>";if("_Process"===a.ctor)return"<process:"+a.id+">";if("::"===a.ctor){b="["+d(a._0);for(a=a._1;"::"===a.ctor;)b+=","+d(a._0),a=a._1;return b+"]"}if("[]"===a.ctor)return"[]";
if("Set_elm_builtin"===a.ctor)return"Set.fromList "+d(_elm_lang$core$Set$toList(a));if("RBNode_elm_builtin"===a.ctor||"RBEmpty_elm_builtin"===a.ctor)return"Dict.fromList "+d(_elm_lang$core$Dict$toList(a));b="";for(var e in a)if("ctor"!==e){c=d(a[e]);var t=c[0];t="{"===t||"("===t||"<"===t||'"'===t||0>c.indexOf(" ");b+=" "+(t?c:"("+c+")")}return a.ctor+b}if("object"===b){if(a instanceof Date)return"<"+a.toString()+">";if(a.elm_web_socket)return"<websocket>";b=[];for(c in a)b.push(c+" = "+d(a[c]));return 0===
b.length?"{}":"{ "+b.join(", ")+" }"}return"<internal structure>"}function g(a,b){a=a.replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/\t/g,"\\t").replace(/\r/g,"\\r").replace(/\v/g,"\\v").replace(/\0/g,"\\0");return b?a.replace(/'/g,"\\'"):a.replace(/"/g,'\\"')}var t=0,M={ctor:"[]"};return{eq:function(a,d){var c=[];a=b(a,d,0,c);for(var g;a&&(g=c.pop());)a=b(g.x,g.y,0,c);return a},cmp:a,Tuple0:{ctor:"_Tuple0"},Tuple2:function(a,b){return{ctor:"_Tuple2",_0:a,_1:b}},chr:function(a){return new String(a)},
update:function(a,b){var d={},c;for(c in a)d[c]=a[c];for(c in b)d[c]=b[c];return d},guid:function(a){return t++},append:e(function(a,b){if("string"===typeof a)return a+b;if("[]"===a.ctor)return b;var d={ctor:"::",_0:a._0,_1:M},c=d;for(a=a._1;"[]"!==a.ctor;)c._1={ctor:"::",_0:a._0,_1:M},a=a._1,c=c._1;c._1=b;return d}),crash:function(a,b){return function(d){throw Error("Ran into a `Debug.crash` in module `"+a+"` "+c(b)+"\nThe message provided by the code author is:\n\n    "+d);}},crashCase:function(a,
b,g){return function(e){throw Error("Ran into a `Debug.crash` in module `"+a+"`\n\nThis was caused by the `case` expression "+c(b)+".\nOne of the branches ended with a crash and the following value got through:\n\n    "+d(g)+"\n\nThe message provided by the code author is:\n\n    "+e);}},toString:d}}();e(function(b,a){return l(b,a._0,a._1)});h(function(b,a,c){return b({ctor:"_Tuple2",_0:a,_1:c})});h(function(b,a,c){return l(b,c,a)});e(function(b,a){return b});var f=f||{};f["<|"]=e(function(b,a){return b(a)});
f=f||{};f["|>"]=e(function(b,a){return a(b)});f=f||{};f[">>"]=h(function(b,a,c){return a(b(c))});f=f||{};f["<<"]=h(function(b,a,c){return b(a(c))});f=f||{};f["++"]=k.append;var V=k.toString;f=f||{};f["||"]=p.or;f=f||{};f["&&"]=p.and;f=f||{};f[">="]=p.ge;f=f||{};f["<="]=p.le;f=f||{};f[">"]=p.gt;f=f||{};f["<"]=p.lt;f=f||{};f["/="]=p.neq;f=f||{};f["=="]=p.eq;f=f||{};f["^"]=p.exp;f=f||{};f["%"]=p.mod;f=f||{};f["//"]=p.div;f=f||{};f["/"]=p.floatDiv;f=f||{};f["*"]=p.mul;f=f||{};f["-"]=p.sub;f=f||{};f["+"]=
p.add;e(function(b,a){return"Just"===a.ctor?a._0:b});var C={ctor:"Nothing"};e(function(b,a){return"Just"===a.ctor?b(a._0):C});var E=function(b){return{ctor:"Just",_0:b}};e(function(b,a){return"Just"===a.ctor?E(b(a._0)):C});h(function(b,a,c){return"Just"===a.ctor&&"Just"===c.ctor?E(l(b,a._0,c._0)):C});m(function(b,a,c,d){return"Just"===a.ctor&&"Just"===c.ctor&&"Just"===d.ctor?E(n(b,a._0,c._0,d._0)):C});u(function(b,a,c,d,g){return"Just"===a.ctor&&"Just"===c.ctor&&"Just"===d.ctor&&"Just"===g.ctor?E(G(b,
a._0,c._0,d._0,g._0)):C});v(function(b,a,c,d,g,e){return"Just"===a.ctor&&"Just"===c.ctor&&"Just"===d.ctor&&"Just"===g.ctor&&"Just"===e.ctor?E(I(b,a._0,c._0,d._0,g._0,e._0)):C});var r=function(){function b(a,b){return{ctor:"::",_0:a,_1:b}}function a(a){for(var c=d,g=a.length;g--;)c=b(a[g],c);return c}function c(a){for(var b=[];"[]"!==a.ctor;)b.push(a._0),a=a._1;return b}var d={ctor:"[]"};return{Nil:d,Cons:b,cons:e(b),toArray:c,fromArray:a,foldr:h(function(a,b,d){d=c(d);for(var g=d.length;g--;)b=l(a,
d[g],b);return b}),map2:h(function(b,d,c){for(var g=[];"[]"!==d.ctor&&"[]"!==c.ctor;)g.push(l(b,d._0,c._0)),d=d._1,c=c._1;return a(g)}),map3:m(function(b,d,c,e){for(var g=[];"[]"!==d.ctor&&"[]"!==c.ctor&&"[]"!==e.ctor;)g.push(n(b,d._0,c._0,e._0)),d=d._1,c=c._1,e=e._1;return a(g)}),map4:u(function(b,d,c,e,f){for(var g=[];"[]"!==d.ctor&&"[]"!==c.ctor&&"[]"!==e.ctor&&"[]"!==f.ctor;)g.push(G(b,d._0,c._0,e._0,f._0)),d=d._1,c=c._1,e=e._1,f=f._1;return a(g)}),map5:v(function(b,d,c,e,f,h){for(var g=[];"[]"!==
d.ctor&&"[]"!==c.ctor&&"[]"!==e.ctor&&"[]"!==f.ctor&&"[]"!==h.ctor;)g.push(I(b,d._0,c._0,e._0,f._0,h._0)),d=d._1,c=c._1,e=e._1,f=f._1,h=h._1;return a(g)}),sortBy:e(function(b,d){return a(c(d).sort(function(a,d){return k.cmp(b(a),b(d))}))}),sortWith:e(function(b,d){return a(c(d).sort(function(a,d){a=b(a)(d).ctor;return"EQ"===a?0:"LT"===a?-1:1}))})}}();e(function(b,a){for(;;){if(1>k.cmp(b,0))return a;var c=a;if("[]"===c.ctor)return a;a=c._1;--b}});var W=r.map2,N=e(function(b,a){for(;;){if("[]"===a.ctor)return!1;
if(b(a._0))return!0;a=a._1}});e(function(b,a){return!l(N,function(a){return!b(a)},a)});var A=r.foldr,J=h(function(b,a,c){for(;;){var d=c;if("[]"===d.ctor)return a;c=b;a=l(b,d._0,a);d=d._1;b=c;c=d}}),X=function(b){return n(J,e(function(a,b){return b+1}),0,b)};e(function(b,a){return l(N,function(a){return k.eq(a,b)},a)});var O=O||{};O["::"]=r.cons;var Y=e(function(b,a){return n(A,e(function(a,d){return{ctor:"::",_0:b(a),_1:d}}),{ctor:"[]"},a)});e(function(b,a){var c=e(function(a,c){return b(a)?{ctor:"::",
_0:a,_1:c}:c});return n(A,c,{ctor:"[]"},a)});var Z=h(function(b,a,c){b=b(a);return"Just"===b.ctor?{ctor:"::",_0:b._0,_1:c}:c});e(function(b,a){return n(A,Z(b),{ctor:"[]"},a)});var P=function(b){return n(J,e(function(a,b){return{ctor:"::",_0:a,_1:b}}),{ctor:"[]"},b)};h(function(b,a,c){var d=e(function(a,d){return"::"===d.ctor?{ctor:"::",_0:l(b,a,d._0),_1:d}:{ctor:"[]"}});return P(n(J,d,{ctor:"::",_0:a,_1:{ctor:"[]"}},c))});var aa=e(function(b,a){return"[]"===a.ctor?b:n(A,e(function(a,b){return{ctor:"::",
_0:a,_1:b}}),a,b)});e(function(b,a){return n(A,aa,{ctor:"[]"},l(Y,b,a))});e(function(b,a){var c=e(function(a,c){var d=c._0;c=c._1;return b(a)?{ctor:"_Tuple2",_0:{ctor:"::",_0:a,_1:d},_1:c}:{ctor:"_Tuple2",_0:d,_1:{ctor:"::",_0:a,_1:c}}});return n(A,c,{ctor:"_Tuple2",_0:{ctor:"[]"},_1:{ctor:"[]"}},a)});e(function(b,a){if("[]"===a.ctor)return{ctor:"[]"};var c=e(function(a,c){return{ctor:"::",_0:b,_1:{ctor:"::",_0:a,_1:c}}});c=n(A,c,{ctor:"[]"},a._1);return{ctor:"::",_0:a._0,_1:c}});var ba=h(function(b,
a,c){for(;;){if(1>k.cmp(b,0))return c;var d=a;if("[]"===d.ctor)return c;a=d._1;c={ctor:"::",_0:d._0,_1:c};--b}}),ca=e(function(b,a){return P(n(ba,b,a,{ctor:"[]"}))}),Q=h(function(b,a,c){if(1>k.cmp(a,0))return{ctor:"[]"};a:do{b:do{if("[]"===c.ctor)return c;if("::"===c._1.ctor)switch(a){case 1:break b;case 2:return{ctor:"::",_0:c._0,_1:{ctor:"::",_0:c._1._0,_1:{ctor:"[]"}}};case 3:if("::"===c._1._1.ctor)return{ctor:"::",_0:c._0,_1:{ctor:"::",_0:c._1._0,_1:{ctor:"::",_0:c._1._1._0,_1:{ctor:"[]"}}}};
break a;default:if("::"===c._1._1.ctor&&"::"===c._1._1._1.ctor){var d=c._1._1._0,e=c._1._0,t=c._0,f=c._1._1._1._0;c=c._1._1._1._1;return 0<k.cmp(b,1E3)?{ctor:"::",_0:t,_1:{ctor:"::",_0:e,_1:{ctor:"::",_0:d,_1:{ctor:"::",_0:f,_1:l(ca,a-4,c)}}}}:{ctor:"::",_0:t,_1:{ctor:"::",_0:e,_1:{ctor:"::",_0:d,_1:{ctor:"::",_0:f,_1:n(Q,b+1,a-4,c)}}}}}break a}else if(1===a)break b;else break a}while(0);return{ctor:"::",_0:c._0,_1:{ctor:"[]"}}}while(0);return c});e(function(b,a){return n(Q,0,b,a)});var da=h(function(b,
a,c){for(;;){if(1>k.cmp(a,0))return b;--a;var d=c;b={ctor:"::",_0:c,_1:b};c=d}});e(function(b,a){return n(da,{ctor:"[]"},b,a)});var ea=h(function(b,a,c){for(;;)if(1>k.cmp(b,a))c={ctor:"::",_0:a,_1:c},--a;else return c}),R=e(function(b,a){return n(ea,b,a,{ctor:"[]"})});e(function(b,a){return n(W,b,l(R,0,X(a)-1),a)});var K=function(){return{fromCode:function(b){return k.chr(String.fromCharCode(b))},toCode:function(b){return b.charCodeAt(0)},toUpper:function(b){return k.chr(b.toUpperCase())},toLower:function(b){return k.chr(b.toLowerCase())},
toLocaleUpper:function(b){return k.chr(b.toLocaleUpperCase())},toLocaleLower:function(b){return k.chr(b.toLocaleLowerCase())}}}().toCode;p=h(function(b,a,c){c=K(c);return-1<k.cmp(c,K(b))&&1>k.cmp(c,K(a))});l(p,k.chr("A"),k.chr("Z"));l(p,k.chr("a"),k.chr("z"));l(p,k.chr("0"),k.chr("9"));l(p,k.chr("0"),k.chr("7"));var w=function(){function b(a){return{ctor:"_Task_succeed",value:a}}function a(a){return{ctor:"_Task_nativeBinding",callback:a,cancel:null}}function c(a){a={ctor:"_Process",id:k.guid(),root:a,
stack:null,mailbox:[]};f(a);return a}function d(a,b){a.mailbox.push(b);f(a)}function g(a,b){for(;1E4>a;){var d=b.root.ctor;if("_Task_succeed"===d){for(;b.stack&&"_Task_onError"===b.stack.ctor;)b.stack=b.stack.rest;if(null===b.stack)break;b.root=b.stack.callback(b.root.value);b.stack=b.stack.rest;++a}else if("_Task_fail"===d){for(;b.stack&&"_Task_andThen"===b.stack.ctor;)b.stack=b.stack.rest;if(null===b.stack)break;b.root=b.stack.callback(b.root.value);b.stack=b.stack.rest;++a}else if("_Task_andThen"===
d)b.stack={ctor:"_Task_andThen",callback:b.root.callback,rest:b.stack},b.root=b.root.task,++a;else if("_Task_onError"===d)b.stack={ctor:"_Task_onError",callback:b.root.callback,rest:b.stack},b.root=b.root.task,++a;else{if("_Task_nativeBinding"===d){b.root.cancel=b.root.callback(function(a){b.root=a;f(b)});break}if("_Task_receive"===d){d=b.mailbox;if(0===d.length)break;b.root=b.root.callback(d.shift());++a}else throw Error(d);}}if(1E4>a)return a+1;f(b);return a}function f(a){m.push(a);l||(setTimeout(h,
0),l=!0)}function h(){for(var a=0,b;1E4>a&&(b=m.shift());)b.root&&(a=g(a,b));b?setTimeout(h,0):l=!1}var l=!1,m=[];return{succeed:b,fail:function(a){return{ctor:"_Task_fail",value:a}},nativeBinding:a,andThen:e(function(a,b){return{ctor:"_Task_andThen",callback:a,task:b}}),onError:e(function(a,b){return{ctor:"_Task_onError",callback:a,task:b}}),receive:function(a){return{ctor:"_Task_receive",callback:a}},spawn:function(d){return a(function(a){var e=c(d);a(b(e))})},kill:function(d){return a(function(a){var c=
d.root;"_Task_nativeBinding"===c.ctor&&c.cancel&&c.cancel();d.root=null;a(b(k.Tuple0))})},sleep:function(d){return a(function(a){var c=setTimeout(function(){a(b(k.Tuple0))},d);return function(){clearTimeout(c)}})},send:e(function(c,e){return a(function(a){d(c,e);a(b(k.Tuple0))})}),rawSpawn:c,rawSend:d}}();p=function(){function b(a,b){return function(a){}}function a(a,b,d,e){function f(a){w.rawSend(fa,a)}var t={},S,h=w.nativeBinding(function(b){var c=a._0;S=e(f,c);var g=a._1,h=d(c);p(t,g,h);b(w.succeed(c))}),
fa=g(h,function(a,c){return w.nativeBinding(function(e){var g=l(b,a,c);c=g._0;S(c);g=g._1;var f=d(c);p(t,g,f);e(w.succeed(c))})});return(h=c(t,f))?{ports:h}:{}}function c(a,b){var c;for(c in x){var e=x[c];if(e.isForeign){var g=g||{};g[c]="cmd"===e.tag?z(c):A(c,b)}a[c]=d(e,b)}return g}function d(a,b){var d={main:b,self:void 0},c=a.tag,e=a.onEffects,f=a.onSelfMsg;a=g(a.init,function(a,b){if("self"===a.ctor)return n(f,d,a._0,b);a=a._0;switch(c){case "cmd":return n(e,d,a.cmds,b);case "sub":return n(e,
d,a.subs,b);case "fx":return G(e,d,a.cmds,a.subs,b)}});return d.self=a}function g(a,b){function d(a){var e=w.receive(function(d){return b(d,a)});return l(c,d,e)}var c=w.andThen;a=l(c,d,a);return w.rawSpawn(a)}function f(a){return function(b){return{type:"leaf",home:a,value:b}}}function m(a){return{type:"node",branches:a}}function p(a,b,d){var c={};q(!0,b,c,null);q(!1,d,c,null);for(var e in a)w.rawSend(a[e],{ctor:"fx",_0:e in c?c[e]:{cmds:r.Nil,subs:r.Nil}})}function q(a,b,d,c){switch(b.type){case "leaf":var e=
b.home;c=u(a,e,c,b.value);b=(b=d[e])||{cmds:r.Nil,subs:r.Nil};a?b.cmds=r.Cons(c,b.cmds):b.subs=r.Cons(c,b.subs);d[e]=b;break;case "node":for(e=b.branches;"[]"!==e.ctor;)q(a,e._0,d,c),e=e._1;break;case "map":q(a,b.tree,d,{tagger:b.tagger,rest:c})}}function u(a,b,d,c){return l(a?x[b].cmdMap:x[b].subMap,function(a){for(var b=d;b;)a=b.tagger(a),b=b.rest;return a},c)}function v(a){if(a in x)throw Error("There can only be one port named `"+a+"`, but your program has multiple.");}function z(a){var b=[],
d=x[a].converter,c=w.succeed(null);x[a].init=c;x[a].onEffects=h(function(a,e,g){for(;"[]"!==e.ctor;){a=b;g=d(e._0);for(var f=0;f<a.length;f++)a[f](g);e=e._1}return c});return{subscribe:function(a){b.push(a)},unsubscribe:function(a){b=b.slice();a=b.indexOf(a);0<=a&&b.splice(a,1)}}}function A(a,b){function d(a,b,d){g=b;return m}function c(a){for(var d=g;"[]"!==d.ctor;)b(d._0(a)),d=d._1}var e=[],g=r.Nil,f=x[a].converter,t=function(a,b,g){a=d(a,b,g);for(b=0;b<e.length;b++)c(e[b]);e=null;k=c;t=d;return a},
k=function(a){e.push(a)},m=w.succeed(null);x[a].init=m;x[a].onEffects=h(function(a,b,d){return t(a,b,d)});return{send:function(b){b=l(_elm_lang$core$Json_Decode$decodeValue,f,b);if("Err"===b.ctor)throw Error("Trying to send an unexpected type of value through port `"+a+"`:\n"+b._0);k(b._0)}}}var x={},B=e(function(a,b){return b}),C=e(function(a,b){return function(d){return a(b(d))}});return{sendToApp:e(function(a,b){return w.nativeBinding(function(d){a.main(b);d(w.succeed(k.Tuple0))})}),sendToSelf:e(function(a,
b){return l(w.send,a.self,{ctor:"self",_0:b})}),effectManagers:x,outgoingPort:function(a,b){v(a);x[a]={tag:"cmd",cmdMap:B,converter:b,isForeign:!0};return f(a)},incomingPort:function(a,b){v(a);x[a]={tag:"sub",subMap:C,converter:b,isForeign:!0};return f(a)},htmlToProgram:function(a){var b=m(r.Nil),d=k.Tuple2(k.Tuple0,b);return _elm_lang$virtual_dom$VirtualDom$program({init:d,view:function(a){return main},update:e(function(a,b){return d}),subscriptions:function(a){return b}})},program:function(d){return function(c){return function(c,
e){c.worker=function(c){if("undefined"!==typeof c)throw Error("The `"+e+"` module does not need flags.\nCall "+e+".worker() with no arguments and you should be all set!");return a(d.init,d.update,d.subscriptions,b)}}}},programWithFlags:function(d){return function(c){return function(e,g){e.worker=function(e){if("undefined"===typeof c)throw Error("Are you trying to sneak a Never value into Elm? Trickster!\nIt looks like "+g+".main is defined with `programWithFlags` but has type `Program Never`.\nUse `program` instead if you do not want flags.");
e=l(_elm_lang$core$Native_Json.run,c,e);if("Err"===e.ctor)throw Error(g+".worker(...) was called with an unexpected argument.\nI tried to convert it to an Elm value, but ran into this problem:\n\n"+e._0);return a(d.init(e._0),d.update,d.subscriptions,b)}}}},initialize:a,leaf:f,batch:m,map:e(function(a,b){return{type:"map",tagger:a,tree:b}})}}();var T=p.batch;T({ctor:"[]"});var D=D||{};D["!"]=e(function(b,a){return{ctor:"_Tuple2",_0:b,_1:T(a)}});D=p.batch;D({ctor:"[]"});e(function(b,a){return"Ok"===
a.ctor?a._0:b});var q=function(b){return{ctor:"Err",_0:b}};e(function(b,a){return"Ok"===a.ctor?b(a._0):q(a._0)});var z=function(b){return{ctor:"Ok",_0:b}};e(function(b,a){return"Ok"===a.ctor?z(b(a._0)):q(a._0)});h(function(b,a,c){return"Ok"===a.ctor?"Ok"===c.ctor?z(l(b,a._0,c._0)):q(c._0):q(a._0)});m(function(b,a,c,d){return"Ok"===a.ctor?"Ok"===c.ctor?"Ok"===d.ctor?z(n(b,a._0,c._0,d._0)):q(d._0):q(c._0):q(a._0)});u(function(b,a,c,d,e){return"Ok"===a.ctor?"Ok"===c.ctor?"Ok"===d.ctor?"Ok"===e.ctor?
z(G(b,a._0,c._0,d._0,e._0)):q(e._0):q(d._0):q(c._0):q(a._0)});v(function(b,a,c,d,e,f){return"Ok"===a.ctor?"Ok"===c.ctor?"Ok"===d.ctor?"Ok"===e.ctor?"Ok"===f.ctor?z(I(b,a._0,c._0,d._0,e._0,f._0)):q(f._0):q(e._0):q(d._0):q(c._0):q(a._0)});e(function(b,a){return"Ok"===a.ctor?z(a._0):q(b(a._0))});e(function(b,a){return"Just"===a.ctor?z(a._0):q(b)});(function(){return{crash:function(b){throw Error(b);},log:e(function(b,a){b=b+": "+k.toString(a);var c=c||{};c.stdout?c.stdout.write(b):console.log(b);return a})}})();
D=function(){function b(a,b){for(var d="";0<a;)a&1&&(d+=b),a>>=1,b+=b;return d}function a(a){return q("could not convert string '"+a+"' to an Int")}function c(a){return q("could not convert string '"+a+"' to a Float")}return{isEmpty:function(a){return 0===a.length},cons:e(function(a,b){return a+b}),uncons:function(a){var b=a[0];return b?E(k.Tuple2(k.chr(b),a.slice(1))):C},append:e(function(a,b){return a+b}),concat:function(a){return r.toArray(a).join("")},length:function(a){return a.length},map:e(function(a,
b){b=b.split("");for(var d=b.length;d--;)b[d]=a(k.chr(b[d]));return b.join("")}),filter:e(function(a,b){return b.split("").map(k.chr).filter(a).join("")}),reverse:function(a){return a.split("").reverse().join("")},foldl:h(function(a,b,c){for(var d=c.length,e=0;e<d;++e)b=l(a,k.chr(c[e]),b);return b}),foldr:h(function(a,b,c){for(var d=c.length;d--;)b=l(a,k.chr(c[d]),b);return b}),split:e(function(a,b){return r.fromArray(b.split(a))}),join:e(function(a,b){return r.toArray(b).join(a)}),repeat:e(b),slice:h(function(a,
b,c){return c.slice(a,b)}),left:e(function(a,b){return 1>a?"":b.slice(0,a)}),right:e(function(a,b){return 1>a?"":b.slice(-a)}),dropLeft:e(function(a,b){return 1>a?b:b.slice(a)}),dropRight:e(function(a,b){return 1>a?b:b.slice(0,-a)}),pad:h(function(a,c,e){a=(a-e.length)/2;return b(Math.ceil(a),c)+e+b(a|0,c)}),padLeft:h(function(a,c,e){return b(a-e.length,c)+e}),padRight:h(function(a,c,e){return e+b(a-e.length,c)}),trim:function(a){return a.trim()},trimLeft:function(a){return a.replace(/^\s+/,"")},
trimRight:function(a){return a.replace(/\s+$/,"")},words:function(a){return r.fromArray(a.trim().split(/\s+/g))},lines:function(a){return r.fromArray(a.split(/\r\n|\r|\n/g))},toUpper:function(a){return a.toUpperCase()},toLower:function(a){return a.toLowerCase()},any:e(function(a,b){for(var c=b.length;c--;)if(a(k.chr(b[c])))return!0;return!1}),all:e(function(a,b){for(var c=b.length;c--;)if(!a(k.chr(b[c])))return!1;return!0}),contains:e(function(a,b){return-1<b.indexOf(a)}),startsWith:e(function(a,
b){return 0===b.indexOf(a)}),endsWith:e(function(a,b){return b.length>=a.length&&b.lastIndexOf(a)===b.length-a.length}),indexes:e(function(a,b){var c=a.length;if(1>c)return r.Nil;for(var d=0,e=[];-1<(d=b.indexOf(a,d));)e.push(d),d+=c;return r.fromArray(e)}),toInt:function(b){var c=b.length;if(0===c)return a(b);var d=b[0];if("0"===d&&"x"===b[1]){for(var e=2;e<c;++e)if(d=b[e],!("0"<=d&&"9">=d||"A"<=d&&"F">=d||"a"<=d&&"f">=d))return a(b);return z(parseInt(b,16))}if("9"<d||"0">d&&"-"!==d&&"+"!==d)return a(b);
for(e=1;e<c;++e)if(d=b[e],"0">d||"9"<d)return a(b);return z(parseInt(b,10))},toFloat:function(a){if(0===a.length||/[\sxbo]/.test(a))return c(a);var b=+a;return b===b?z(b):c(a)},toList:function(a){return r.fromArray(a.split("").map(k.chr))},fromList:function(a){return r.toArray(a).join("")}}}();var ha=D.toUpper,ia=D.cons;e(function(b,a){return{ctor:"_Tuple2",_0:a._0,_1:b(a._1)}});e(function(b,a){return{ctor:"_Tuple2",_0:b(a._0),_1:a._1}});e(function(b,a){return l(f["++"],b,a)});e(function(b,a){return{ctor:"::",
_0:a,_1:b}});e(function(b,a){a=a(b);return{ctor:"_Tuple2",_0:b,_1:a}});var U=e(function(b,a){return b(a)});l(U,function(b){return b*b},5);(function(){return l(U,function(b){return b*b},5)})();var F=F||{};F["++*"]=e(function(b,a){return"[]"===b.ctor?0:n(A,e(function(a,b){return a+b}),0,b)*a});e(function(b,a){return b*a})(2);var L=function(b){return n(A,e(function(a,b){return a+b}),0,b)};e(function(b,a){return L(b)*a});e(function(b,a){return L(a)*b})(2);h(function(b,a,c){return l(f["++"],V(L(b)*a),
c)});l(R,1,4);k.chr("a");e(function(b,a){return l(f["++"],a,ha(l(ia,b,"")))});h(function(b,a,c){return{x:b,y:a,keypressed:c}});e(function(b,a){return{timestamp:b,eventname:a}});h(function(b,a,c){return{title:b,text:a,attachment:c}});u(function(b,a,c,d,e){return{xpos:b,ypos:a,numbertones:c,backgroundimage:d,events:e}});var B={};B.AllBasics=B.AllBasics||{};"undefined"!==typeof _user$project$AllBasics$main&&_user$project$AllBasics$main(B.AllBasics,"AllBasics",void 0);if("function"===typeof define&&define.amd)define([],
function(){return B});else if("object"===typeof module)module.exports=B;else if(F=this.Elm,"undefined"===typeof F)this.Elm=B;else for(var H in B){if(H in F)throw Error("There are two Elm modules called `"+H+"` on this page! Rename one of them.");F[H]=B[H]}}).call(this);
